config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  devise_for :members
  get 'home/index'

  root 'home#index'

  resources :jobs
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    has_one :address
    accepts_nested_attributes_for :address
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
 # before_action :authenticate_member!

  # GET /jobs
  # GET /jobs.json
  
    def index
      @jobs = Job.all
    end
  

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @job.build_address
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Vaga criada com sucesso' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Vaga apagada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:resumo, :cargo, :salario, :vagas, :address_attributes => [:rua, :cep, :telefone, :referencia, :email, :requisito])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :resumo %>
    <%= form.text_area :resumo %>
  </div>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_field :cargo %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario %>
  </div>

  <div class="field">
    <%= form.label :vagas %>
    <%= form.number_field :vagas %>
  </div><br>
  <h1>Dados da Empresa</h1>
  <%= form.fields_for :address do |ff| %><br>
    <div class="field">
      <%= ff.label :rua %>
      <%= ff.text_area :rua %>
    </div>

    <div class="field">
      <%= ff.label :cep %>
      <%= ff.text_field :cep %>
    </div>

    <div class="field">
      <%= ff.label :telefone %>
      <%= ff.phone_field :telefone %>
    </div>

    <div class="field">
      <%= ff.label :referencia %>
      <%= ff.text_area :referencia %>
    </div>

    <div class="field">
      <%= ff.label :email %>
      <%= ff.email_field :email %>
    </div>

    <div class="field">
      <%= ff.label :requisito %>
      <%= ff.text_area :requisito %>
    </div>

  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
 
    <tr>
      <th>Resumo</th>
      <th>Cargo</th>
      <th>Salario</th>
      <th>Vagas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.resumo %></td>
        <td><%= job.cargo %></td>
        <td><%= job.salario %></td>
        <td><%= job.vagas %></td>
        
      
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<td><%= link_to 'Detalhe geral das vagas', addresses_path %></td><br><br>
        
<td><%= link_to 'Voltar ', home_index_path %></td>

<br>

app/views/jobs/new.html.erb
<h1>Dados da Vaga</h1>
<%= render 'form', job: @job %>
<%= link_to 'voltar', home_index_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resumo:</strong>
  <%= @job.resumo %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @job.cargo %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @job.salario %>
</p>

<p>
  <strong>Vagas:</strong>
  <%= @job.vagas %>
</p>

<%= link_to 'voltar', jobs_path%>