config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  devise_for :members
  get 'home/index'

  root 'home#index'

  resources :jobs
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:rua, :cep, :telefone, :referencia, :email, :requisito, :job_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<h1>Dados da Empresa</h1>

<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :referencia %>
    <%= form.text_field :referencia %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :requisito %>
    <%= form.text_field :requisito %>
  </div>

  <div class="field">
    <%= form.label :job_id %>
    <%= form.text_field :job_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalhes</h1>

<table>
  <thead>
    <tr>
      <th>Rua</th>
      <th>Cep</th>
      <th>Telefone</th>
      <th>Referencia</th>
      <th>Email</th>
      <th>Requisito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.rua %></td>
        <td><%= address.cep %></td>
        <td><%= address.telefone %></td>
        <td><%= address.referencia %></td>
        <td><%= address.email %></td>
        <td><%= address.requisito %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to 'Voltar', home_index_path  %></td>
<br>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rua:</strong>
  <%= @address.rua %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @address.cep %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @address.telefone %>
</p>

<p>
  <strong>Referencia:</strong>
  <%= @address.referencia %>
</p>

<p>
  <strong>Email:</strong>
  <%= @address.email %>
</p>

<p>
  <strong>Requisito:</strong>
  <%= @address.requisito %>
</p>

<p>
  <strong>Job:</strong>
  <%= @address.job %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>